apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mem-limit
  name: mem-limit
spec:
  containers:
  - image: nginx
    name: mem-limit
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
