apiVersion: v1
kind: Pod
metadata:
  labels:
    app: multi-container
  name: multi-container-pod
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /var/log/app
    command: ["sh","-c","while true; do [ -f /var/log/app/notes.txt ] && cat /var/log/app/notes.txt; sleep 5; done" ]
  - image: busybox
    name: busybox
    command: [ "sh", "-c", "while true; do echo \"from busybox\" >> /var/log/app/notes.txt ; sleep 3; done" ] 
    volumeMounts:
    - name: shared-data
      mountPath: /var/log/app
  restartPolicy: Always
