apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-app
  name: api-app
  namespace: app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-app
  strategy: {}
  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - command:
            - sleep
            - "3600"
          image: busybox
          name: busybox
          env:
            - name: APP_ENV
              value: "production"
            - name: APP_VERSION
              value: "1.0"
          resources: {}
status: {}
