apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-deploy
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:1.25
          ports:
            - containerPort: 80
