apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    version: v2
  name: web-app-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
      version: v2
  strategy: {}
  template:
    metadata:
      labels:
        app: web-app
        version: v2
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          resources: {}
status: {}
