apiVersion: v1
kind: Pod
metadata:
  labels:
    role: frontend
  name: lable-me
spec:
  containers:
  - image: nginx
    name: lable-me
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
