apiVersion: v1
kind: Pod
metadata:
  labels:
    app: web-app
  name: init-demo
spec:
  containers:
  - image: nginx
    name: web-app
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "echo 'Initializing...'; sleep 3;"]

