apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  template:
    metadata: {}
    spec:
      containers:
        - command: ["sh", "-c", "echo $((3*7))"]
          image: busybox
          name: my-job
      restartPolicy: Never
